#!/usr/bin/env node
// Self-hosts the three families as latin-only woff2 under public/fonts/, and emits
// the @font-face block the site imports. Third-party font CSS is render-blocking
// from a host we do not control; this removes both problems.
//
// Re-run only when a weight or family changes. The output is committed.
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const SITE = path.resolve(HERE, '..')
const FONT_DIR = path.join(SITE, 'public/fonts')

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
const SRC =
  'https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500;600&display=swap'
const KEEP = new Set(['latin', 'latin-ext'])

await mkdir(FONT_DIR, { recursive: true })

const css = await (await fetch(SRC, { headers: { 'User-Agent': UA } })).text()

// Each @font-face is preceded by a /* subset */ comment naming its unicode range.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]
const out = []
const seen = new Set()

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue

  const family = block.match(/font-family:\s*'([^']+)'/)[1]
  const weight = block.match(/font-weight:\s*(\d+)/)[1]
  const url = block.match(/url\((https:\/\/[^)]+)\)/)[1]
  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`

  if (!seen.has(file)) {
    const res = await fetch(url, { headers: { 'User-Agent': UA } })
    if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`)
    await writeFile(path.join(FONT_DIR, file), Buffer.from(await res.arrayBuffer()))
    seen.add(file)
  }

  out.push(
    block
      .replace(/url\(https:\/\/[^)]+\)/, `url(/fonts/${file})`)
      .replace(/^@font-face\s*\{/, '@font-face {')
      .trim(),
  )
}

await writeFile(
  path.join(SITE, 'src/css/fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — latin subsets, self-hosted. Do not edit. */\n\n${out.join('\n\n')}\n`,
)

console.log(`fonts: ${seen.size} woff2 files, ${out.length} @font-face rules`)
